---
driver:
  name: vagrant
  customize:
    natdnshostresolver1: 'on'

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.0.0

platforms:
  - name: centos-6.5
  - name: centos-7

suites:
  - name: oracle-inventory
    run_list:
      - recipe[acx-oracle-inventory::inventory_test]
  - name: oracle-inventory
    run_list:
      - recipe[acx-oracle-inventory::inventory_override_test]