---
driver:
  name: vagrant
  customize:
    natdnshostresolver1: 'on'

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 17
  install_strategy: once

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: centos-8
  - name: oracle-7
  - name: amazon-2

suites:
  - name: default
    run_list:
      - recipe[oracle-inventory-management::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      oracle:
        inventory:
          user: oracle
          group: dba
          location: /opt/oracle/oraInventory
          ora_inst_path: /etc/oraInst.loc
          manage_users: true
          audit_changes: true
          audit_log: /var/log/oracle/inventory_audit.log
          
  - name: backup
    run_list:
      - recipe[oracle-inventory-management::default]
      - recipe[oracle-inventory-management::backup]
    verifier:
      inspec_tests:
        - test/integration/backup
    attributes:
      oracle:
        inventory:
          user: oracle
          group: dba
          location: /opt/oracle/oraInventory
          ora_inst_path: /etc/oraInst.loc
          manage_users: true
          backup_dir: /var/backups/oracle_inventory
          max_backups: 5
          audit_changes: true
          audit_log: /var/log/oracle/inventory_audit.log

  # Test suite for Oracle version support
  - name: oracle-versions
    run_list:
      - recipe[oracle-inventory-management::default]
      - recipe[oracle-inventory-management::test_versions]
    verifier:
      inspec_tests:
        - test/integration/oracle-versions
    attributes:
      oracle:
        inventory:
          user: oracle
          group: dba
          location: /opt/oracle/oraInventory
          ora_inst_path: /etc/oraInst.loc
          manage_users: true
          audit_changes: true
          audit_log: /var/log/oracle/inventory_audit.log
        default_version: '19c'

  # Test suite for Oracle RAC support
  - name: oracle-rac
    run_list:
      - recipe[oracle-inventory-management::default]
      - recipe[oracle-inventory-management::test_rac]
    verifier:
      inspec_tests:
        - test/integration/oracle-rac
    attributes:
      oracle:
        inventory:
          user: oracle
          group: dba
          location: /opt/oracle/oraInventory
          ora_inst_path: /etc/oraInst.loc
          manage_users: true
          audit_changes: true
          audit_log: /var/log/oracle/inventory_audit.log
        default_version: '19c'

  # Test suite for inventory_entry custom resource
  - name: custom-resource
    run_list:
      - recipe[oracle-inventory-management::default]
      - recipe[oracle-inventory-management::test_custom_resource]
    verifier:
      inspec_tests:
        - test/integration/custom-resource
    attributes:
      oracle:
        inventory:
          user: oracle
          group: dba
          location: /opt/oracle/oraInventory
          ora_inst_path: /etc/oraInst.loc
          manage_users: true
          audit_changes: true
          audit_log: /var/log/oracle/inventory_audit.log
        default_version: '19c'