name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install Ruby
      uses: ruby/setup-ruby@v1.238.0
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Build and release Cookbook
      uses: chef/community-cookbook-releaser@main
      env:
        CHEF_LICENSE: accept-no-persist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SUPERMARKET_API_KEY: ${{ secrets.SUPERMARKET_API_KEY }}